### ISSUE TITLE
Doesn't capture issues with ,'s correctly

### ISSUE THREAD

**Issue by charlesmsiegel** [jacob-armiger/comic-list-web-scraper#10]
Issues with commas in either the title or the issue number on CBRO are downloaded incorrectly when using both csv and excel download options.

Examples:
On https://comicbookreadingorders.com/dc/characters/jimmy-olsen-reading-order/ the issues come out as " Jimmy Olsen" instead of "Superman's Pal, Jimmy Olsen" (similar can be seen on the Lois Lane list)
On https://comicbookreadingorders.com/dc/events/dc-one-million-reading-order/ the issues all come out as #1 because CBRO marks them as #1,000,000.

**Comment by jacob-armiger** [comment]
Thanks for letting me know! I'll look at resolving this soon.

**Comment by jacob-armiger** [comment]
I resolved this issue by changing the delimiter to `;` instead of `,`. Everything else should be working properly still from my testing.
