### ISSUE TITLE
A csv or excel file is downloading but the file downloaded is empty

### ISSUE THREAD

**Issue by GoldMight948** [jacob-armiger/comic-list-web-scraper#15]
I just used this and both the csv and excel files come up empty

**Comment by jacob-armiger** [comment]
Thanks for letting me know. It looks like when a request is made to the URL that's pasted by the user, a `403 Forbidden` message is returned. Something may have changed with [comicbookreadingorders.com](comicbookreadingorders.com). I'll look into a fix soon.

**Comment by jacob-armiger** [comment]
Fixed this issue by changing library used to make request. Issue explained [https://stackoverflow.com/questions/74446830/error-status-code-403-even-with-headers-python-requests](here).

**Comment by GoldMight948** [comment]
Thanks for the fix👍
